map $host $root_name {
    default "tiles.styluslabs.com";
}

log_format goaccess_timed '$remote_addr - $remote_user [$time_local] '
                          '"$request" $status $body_bytes_sent '
                          '"$http_referer" "$http_user_agent" '
                          '$request_time $upstream_response_time';

server {
    listen 80;
    listen [::]:80;
    server_name tiles.styluslabs.com ~^tiles-.*\.styluslabs\.com$;
    # inside server block to replace global setting
    access_log /var/log/nginx/access.log goaccess_timed;

    # Redirect acme.sh HTTP-01 challenges to tiles-a (which intiates them)
    location /.well-known/acme-challenge/ {
        if ($hostname != "tiles-a.styluslabs.com") {
            return 301 http://tiles-a.styluslabs.com$request_uri;
        }
        root /var/www/tiles.styluslabs.com;
    }

    location / {
        proxy_pass http://127.0.0.1:8080;

        # Pass along standard proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Redirect all other HTTP traffic to HTTPS
    #location / {
    #    return 301 https://$host$request_uri;
    #}
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name tiles.styluslabs.com ~^tiles-.*\.styluslabs\.com$;
    # inside server block to replace global setting
    access_log /var/log/nginx/access.log goaccess_timed;

    # Use variable in certificate paths to prevent failure at startup due to missing files
    ssl_certificate /etc/nginx/ssl/$root_name.fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/$root_name.key.pem;

    # Hardened SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    # Reverse proxy to your app on localhost:8080
    location / {
        proxy_pass http://127.0.0.1:8080;

        # Pass along standard proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
